# Generated by Django 5.2.11 on 2026-05-09 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_jobattachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemsetting',
            options={'ordering': ['-updated_at', '-id']},
        ),
    ]
