# Generated by Django 5.2.11 on 2026-10-01 09:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_systemsetting_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='job',
            name='discount_reason',
            field=models.TextField(blank=True),
        ),
    ]
