# Generated by Django 5.2.11 on 2026-10-04 20:18

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def create_existing_staff_profiles(apps, schema_editor):
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    StaffProfile = apps.get_model('crm', 'StaffProfile')
    database = schema_editor.connection.alias
    ids = User.objects.using(database).filter(models.Q(is_staff=True) | models.Q(is_superuser=True)).values_list('pk', flat=True)
    StaffProfile.objects.using(database).bulk_create([StaffProfile(staff_id=pk) for pk in ids], ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_expense_paid_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffDailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('expected_start', models.TimeField(blank=True, null=True)),
                ('resumed_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('bonus_recommended', models.BooleanField(default=False)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_records_added', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_staff_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_records_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'staff__first_name', 'id'],
                'constraints': [models.UniqueConstraint(fields=('staff', 'date'), name='one_staff_record_per_day'), models.CheckConstraint(condition=models.Q(('rating__isnull', True), models.Q(('rating__gte', 1), ('rating__lte', 10)), _connector='OR'), name='staff_rating_1_to_10'), models.CheckConstraint(condition=models.Q(('left_at__isnull', True), models.Q(('left_at__gte', models.F('resumed_at')), ('resumed_at__isnull', False)), _connector='OR'), name='staff_departure_after_arrival')],
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_title', models.CharField(blank=True, max_length=120)),
                ('monthly_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('expected_start', models.TimeField(blank=True, null=True)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['staff__first_name', 'staff__username'],
                'constraints': [models.CheckConstraint(condition=models.Q(('monthly_salary__gte', 0)), name='staff_salary_nonnegative')],
            },
        ),
        migrations.RunPython(create_existing_staff_profiles, migrations.RunPython.noop),
    ]
